"""Add file_path and file_name to cases

Revision ID: 1445dabc96a1
Revises: c06a4a8b4525
Create Date: 2026-05-19 18:50:45.485292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1445dabc96a1'
down_revision: Union[str, Sequence[str], None] = 'c06a4a8b4525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('file_path', sa.String(), nullable=True))
    op.add_column('cases', sa.Column('file_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'file_name')
    op.drop_column('cases', 'file_path')
    # ### end Alembic commands ###
