"""add group id and custom role id for cases

Revision ID: 2584cc071e83
Revises: cbe715eace49
Create Date: 2026-06-08 22:54:42.463055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2584cc071e83'
down_revision: Union[str, Sequence[str], None] = 'cbe715eace49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('cases', sa.Column('custom_role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cases', 'groups', ['group_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'cases', 'custom_roles', ['custom_role_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_column('cases', 'custom_role_id')
    op.drop_column('cases', 'group_id')
    # ### end Alembic commands ###
