"""Added is_archived to cases

Revision ID: 277133ed4936
Revises: c8152a478b96
Create Date: 2026-06-16 21:08:08.421847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '277133ed4936'
down_revision: Union[str, Sequence[str], None] = 'c8152a478b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'is_archived')
    # ### end Alembic commands ###
