"""Initial migration

Revision ID: 9747f055e1aa
Revises: 
Create Date: 2026-05-09 18:46:25.828633

"""
from typing import Sequence, Union

from alembic import op #type: ignore
import sqlalchemy as sa #type: ignore


# revision identifiers, used by Alembic.
revision: str = '9747f055e1aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
