"""Add summary to cases

Revision ID: b2e76b8f22bf
Revises: 769d269a1ad2
Create Date: 2026-05-10 20:27:17.623536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2e76b8f22bf'
down_revision: Union[str, Sequence[str], None] = '769d269a1ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'summary')
    # ### end Alembic commands ###
