"""Add cascade delete to activity logs

Revision ID: c06a4a8b4525
Revises: d8dfafdbdfe6
Create Date: 2026-05-17 21:39:57.209762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c06a4a8b4525'
down_revision: Union[str, Sequence[str], None] = 'd8dfafdbdfe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('activity_logs_case_id_fkey'), 'activity_logs', type_='foreignkey')
    op.create_foreign_key(None, 'activity_logs', 'cases', ['case_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.create_foreign_key(op.f('activity_logs_case_id_fkey'), 'activity_logs', 'cases', ['case_id'], ['id'])
    # ### end Alembic commands ###
