"""Add recomendation to cases

Revision ID: d8dfafdbdfe6
Revises: b2e76b8f22bf
Create Date: 2026-05-11 18:59:36.143050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8dfafdbdfe6'
down_revision: Union[str, Sequence[str], None] = 'b2e76b8f22bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('recommendation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'recommendation')
    # ### end Alembic commands ###
