"""add cascade del to comment, fix org deletion to follow cascade

Revision ID: dd791db58d97
Revises: e0d95bc3be4d
Create Date: 2026-06-06 22:02:08.898531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd791db58d97'
down_revision: Union[str, Sequence[str], None] = 'e0d95bc3be4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cases_org_id_fkey'), 'cases', type_='foreignkey')
    op.create_foreign_key(None, 'cases', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('comments_author_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_author_id_fkey'), 'comments', 'users', ['author_id'], ['id'])
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.create_foreign_key(op.f('cases_org_id_fkey'), 'cases', 'organizations', ['org_id'], ['id'])
    # ### end Alembic commands ###
